### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [hoangnghiem205/hoangnm-blog#1]
Hi Minh Hoang Nghiem, 

Thanks for your submission! But could you check the link to your blog on Heroku? There is something wrong with it.

**Comment by hoangnghiem205** [comment]
Thank you for reviewing my site. The bug is fixed

**Comment by coderschoolreview** [comment]
Thanks for the update!! Love the styling of your blog app. Nice work!

Looks like you still have problems with paths to images ![](https://dl.dropboxusercontent.com/spa/vkwvskbavc27sn4/7h88sfl_.png)

The problem is that you're not displaying images correctly because of this [code](https://github.com/hoangnghiem205/hoangnm-blog/blob/master/app/views/welcome/index.html.erb#L6)

```
# Don't do this
<img class="article-image" src="assets/<%= article.image %>" border="0" alt="">
```

Consider this instead:

``` erb
<%= image_tag article.image, class: "article-image", border: 0, alt: "article image" %>
```

**Comment by hoangnghiem205** [comment]
thanks @coderschoolreview 
i have fixed it

**Comment by coderschoolreview** [comment]
Hi @hoangnghiem205, did you push your latest changes to GitHub? Your last commit was 8 days ago :/

**Comment by hoangnghiem205** [comment]
my last commit was 5 days ago - "fix image err"
i pushed to heroku but Github was forgotten
